// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateUserFriendship create user friendship
//
// swagger:model CreateUserFriendship
type CreateUserFriendship struct {

	// friend name
	// Example: user_123
	// Required: true
	FriendName *string `json:"friend_name"`

	// user name
	// Example: user_124
	// Required: true
	UserName *string `json:"user_name"`

	// user photo
	// Example: https://image_path
	UserPhoto string `json:"user_photo,omitempty"`
}

// Validate validates this create user friendship
func (m *CreateUserFriendship) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFriendName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateUserFriendship) validateFriendName(formats strfmt.Registry) error {

	if err := validate.Required("friend_name", "body", m.FriendName); err != nil {
		return err
	}

	return nil
}

func (m *CreateUserFriendship) validateUserName(formats strfmt.Registry) error {

	if err := validate.Required("user_name", "body", m.UserName); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create user friendship based on context it is used
func (m *CreateUserFriendship) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateUserFriendship) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateUserFriendship) UnmarshalBinary(b []byte) error {
	var res CreateUserFriendship
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
