// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SendMessage send message
//
// swagger:model SendMessage
type SendMessage struct {

	// friend name
	// Example: user_123
	// Required: true
	FriendName *string `json:"friend_name"`

	// message
	// Example: some message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this send message
func (m *SendMessage) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFriendName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SendMessage) validateFriendName(formats strfmt.Registry) error {

	if err := validate.Required("friend_name", "body", m.FriendName); err != nil {
		return err
	}

	return nil
}

func (m *SendMessage) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("message", "body", m.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this send message based on context it is used
func (m *SendMessage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SendMessage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SendMessage) UnmarshalBinary(b []byte) error {
	var res SendMessage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
